version: "3.9"

services:
  backend:
    build: ./strapi-backend
    container_name: strapi-backend
    restart: always
    ports:
      - "1337:1337"
    env_file:
      - ./strapi-backend/.env
    # depends_on:
    #   - db
    volumes:
      - ./strapi-backend/public/uploads:/App/public/uploads

  # db:
  #   image: postgres:17-alpine
  #   container_name: pg-container
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: aku_zeliang
  #   restart: unless-stopped
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - /var/lib/postgresql/data:/var/lib/postgresql/data
